version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  web:
    build: .
    container_name: web  
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DancingCheetah821&
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: DancingCheetah821&
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:

